import Head from 'next/head'
import { Hero } from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Photon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Slider slides={SliderData} />

    </div>
  )
}
